### ISSUE TITLE
use for another spix.x

### ISSUE THREAD

**Issue by mayurpatelgec** [deeplyembeddedWP/BeagleBone-SPI-Library#1]
hi. i found your great work for BBB and for AM335x.
I am working on with second spi2.0 and my board(Tqma 335x) has AM3352(**same as BBB**).

So i have already done **device tree** changes for spi and activated it (/dev/spi2.0) . Now is it possible to use your spi library for my use? i saw `#define SPIDEV1_PATH                     "/dev/spidev1.0"` in your spi.h .. is it the only change ? Thank you in advance. :)

**Comment by vinay-divakar** [comment]
Yes, that's right. I will be closing this thread as this is not an issue but rather a question regarding the usage.

**Comment by mayurpatelgec** [comment]
ok thank you i will try it down and post the comments later on.
